[workspace]
members = [
    "render",
    "render/macros",
    "render-extra",
    "render-gl",
    "render-boilerplate",
    "render-test",
    "shader/macros",
    "spirv",
    "style-test",
    "imgui",
    "xxgui",
]

[profile.release]
debug = true
