#cargo-features = ["edition"]

[profile.release]
debug = true

[package]
name = "gfx2"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
build = "build.rs"
#edition = '2018'

[build-dependencies]
gl_generator = "*"
embed-resource = "*"

[dev-dependencies]
nalgebra-glm = "*"

[dependencies]
#petgraph = { version = "*", features = ["serde-1"] }
bitflags = "*"
toml = "0.4"
config = "*"
winit = "*"
glutin = "*"
pretty_env_logger = "*"
log = "*"
slotmap = { version = "*", features = ["unstable"] }
serde = "*"
serde_derive = "*"
downcast-rs = "*"
time = "*"
sid_vec = "*"
regex="*"
smallvec = "*"
lazy_static = "*"
shaderc = "*"
ordered-float = "*"
unreachable = "*"
typed-arena = "*"

#[target.'cfg(windows)'.dependencies]
#winapi = { version = "*", features = ["windef", "winuser"] }

#[target.'cfg(target_os = "macos")'.dependencies]
#metal-rs = "*"
#cocoa = "*"
#objc = "*"