[workspace]
members = [
    "api",
    "api/macros",
    "api-extra",
    "api-gl",
    "api-boilerplate",
    "api-test",
    "shader/macros",
    "spirv",
    "style-test",
    "imgui",
    "xxgui",
]

[profile.release]
debug = true
