#cargo-features = ["edition"]

[profile.release]
debug = true

[package]
name = "gfx2"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
#edition = '2018'

[dependencies]
petgraph = { version = "*", features = ["serde-1"] }
bitflags = "*"
toml = "0.4"
config = "*"
winit = "*"
ash = "*"
pretty_env_logger = "*"
log = "*"
slotmap = "*"
serde = "*"
serde_derive = "*"
downcast-rs = "*"
time = "*"
sid_vec = "*"

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["windef", "winuser"] }

[target.'cfg(target_os = "macos")'.dependencies]
metal-rs = "*"
cocoa = "*"
objc = "*"