[workspace]
members = [
    "derive",
    "renderer",
    "backend_gl",
    "spirv",
    "shader_macros",
    "common_shaders",
    "extension_runtime",
    # for testing
    "extension_runtime/tests/test_dylib"
]

[profile.release]
debug = true
