[vars]
width = 1280
height = 720

[images.target]
width = "$width"
height = "$height"
format = "R8G8B8A8_SRGB"

[images.diffuse]
width = "$width"
height = "$height"
format = "R16G16B16A16_SFLOAT"

[images.normals]
width = "$width"
height = "$height"
format = "R16G16B16A16_SFLOAT"

[images.tangents]
width = "$width"
height = "$height"
format = "R16G16B16A16_SFLOAT"

[images.depth]
width = "$width"
height = "$height"
format = "R32_SFLOAT"

[tasks.gbuffers]
color_attachments = [
    { index = 0, id = "diffuse@init" },
    { index = 1, id = "normals@init" },
    { index = 2, id = "tangents@init" },
    { index = 3, id = "depth@init" }]

[tasks.postprocess]
image_sample = [
    "diffuse@gbuffers",
    "normals@gbuffers",
    "tangents@gbuffers",
    "depth@gbuffers"]
color_attachments = [
    { index = 0, id = "target@init" }]

[[present]]
id = "target@postprocess"