[package]
name = "gfx2-derive"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
edition = "2018"

[dev-dependencies]
gfx2 = { path = "../renderer" }

[dependencies]
log = "*"
quote = "0.6.10"
syn = "0.15.23"
darling = "0.8.1"
proc-macro2 = "0.4.24"

[lib]
proc-macro = true