[package]
name = "autograph-api-test"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
edition = '2018'

[dependencies]
autograph-api-gl = { path = "../api-gl" }
autograph-api = { path = "../api" }
glutin = "0.19.0"
config = "0.9.2"
