[package]
name = "autograph-render-extra"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
edition = '2018'

[dependencies]
autograph-render = { path = "../render" }
petgraph = "0.4.13"
derivative = "1.0.2"
