[package]
name = "gfx2_derive"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
edition = "2018"

[dev-dependencies]
gfx2 = { path = "../" }

[dependencies]
log = "*"
quote = "*"
syn = "*"
darling = "*"
proc-macro2 = "*"

[lib]
proc-macro = true