[package]
name = "gfx2-spirv"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
edition = '2018'

[dependencies]
byteorder = "*"
num-traits = "*"
log = "*"
spirv_headers = "*"
ordered-float = "*"
typed-arena = "*"
gfx2 = { path = "../renderer" }
