[package]
name = "autograph-spirv"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
edition = '2018'


[dependencies]
byteorder = "1.2.7"
num-traits = "0.2.6"
log = "0.4.6"
spirv_headers = "1.3.4"
ordered-float = "1.0.1"
typed-arena = "1.4.1"

