[package]
name = "openimageio"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
edition = "2018"

[dependencies]
openimageio-sys = {path = "../openimageio-sys"}
libc = "*"
regex = "1.1.0"
itertools = "0.8.0"